#+TITLE: Org Mode - ¡Organizá Tu Vida En Texto Plano!
#+LANGUAGE:  es
#+AUTHOR: Alvar Maciel, Niv Sardí, Vladimir Di Fiore. En base al trabajo de Bernt Hansen (IRC:Thumper_ on freenode)
#+EMAIL: alvarmaciel@gmail.com
#+OPTIONS:   H:3 num:t   toc:2 \n:nil @:t ::t |:t ^:nil -:t f:t *:t <:nil
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+OPTIONS:   author:t creator:t timestamp:t email:t
#+DESCRIPTION: A description of how I currently use org-mode
#+KEYWORDS:  org-mode Emacs organization GTD getting-things-done git
#+SEQ_TODO: FIXME FIXED
#+INFOJS_OPT: view:nil toc:t ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 

Org-mode es una fabulosa herramienta de organización construida por Carsten Dominik
que opera en archivos de texto plano. Org-mode es parte de Emacs.

Este documento asume que ya ha tenido algún contacto con org-mode también con los
conceptos como: agenda, el modo de captura, etc. Estos no serán completamente
extraños para ti. Más información acerca de org-mode puede ser encontrado en:
[[http://orgmode.org/index.html#sec-4.1][Manual de org-mode]] y [[http://orgmode.org/worg/][Worg Site]]


He estado usando org-mode como mi gestor de información personal por
años. Empecé solamente las con palabras clave default =TODO= y =DONE=. 
Fuí añadido pequeños cambios en mi flujo de trabajo y con el tiempo
a evolucionado hasta convertirse en lo que se describe en este documento.

Todavía cambio  mi flujo de trabajo y pruebo cosas nuevas con regularidad. En este
documento se describen los flujos de trabajo maduros en mi actual configuración de org-mode. 
Tiendo a documentar los cambios en mi flujo de trabajo cada 30 días después de la aplicación de
ellos (suponiendo que todavía existen en ese momento) para que el nuevo
flujo de trabajo tenga chance de madurar.

Algunas de las configuraciones personalizadas de Emacs que se describen en este documento están
setadeadas en sus valores predeterminados. Se  muestra explícitamente el seteo de
importantes variables utilizadas en org-mode esto en mantiene el comportamiento de mi
de flujo de trabajo estable en caso de que cambie el valor por defecto
en el futuro.
* Primeros Pasos

Uso =org-mode= en la mayoría de mis buffers de emacs
** Configuración de Org-Mode
:PROPERTIES:
:CUSTOM_ID: Configuración
:END:

La siguiente configuración en el .emacs habilita org-mode para casir todos los buffers.
=org-mode= es el modo por default de los archivos  =.org=, =.org_archive=, and =.txt=

#+begin_src emacs-lisp :tangle yes
  ;;;
  ;;; Org Mode
  ;;;
  (add-to-list 'load-path (expand-file-name "~/git/org-mode/lisp"))
  (add-to-list 'auto-mode-alist '("\\.\\(org\\|org_archive\\|txt\\)$" . org-mode))
  (require 'org-install)
  ;;
  ;; Enlaces de teclas standar
  (global-set-key "\C-cl" 'org-store-link)
  (global-set-key "\C-ca" 'org-agenda)
  (global-set-key "\C-cb" 'org-iswitchb)
#+end_src

=orgstruct++-mode= está habilitado en los mensajes de los buffers de =Gnus= para
ayudar en la creación de mensajes de mail estructurados.

#+begin_src emacs-lisp :tangle yes
  (add-hook 'message-mode-hook 'orgstruct++-mode 'append)
  (add-hook 'message-mode-hook 'turn-on-auto-fill 'append)
  (add-hook 'message-mode-hook 'bbdb-define-all-aliases 'append)
  (add-hook 'message-mode-hook 'orgtbl-mode 'append)
  (add-hook 'message-mode-hook 'turn-on-flyspell 'append)
  (add-hook 'message-mode-hook '(lambda () (setq fill-column 72)) 'append)
  (add-hook 'message-mode-hook '(lambda () (local-set-key (kbd "C-c M-o") 'org-mime-htmlize)) 'append)
#+end_src

=flyspell-mode= está habilitado para casi todo, ayuda en la creación de
documentos sin errores ortográficos.

#+begin_src emacs-lisp :tangle yes
  ;; flyspell para chequear ortografía en TODOS lados
  (add-hook 'org-mode-hook 'turn-on-flyspell 'append)
  
  ;; Disable C-c [ and C-c ] in org-mode
  (add-hook 'org-mode-hook
            (lambda ()
              ;; Undefine C-c [ and C-c ] since this breaks my
              ;; org-agenda files when directories are include It
              ;; expands the files in the directories individually
              (org-defkey org-mode-map "\C-c["    'undefined)
              (org-defkey org-mode-map "\C-c]"    'undefined)) 'append)
  
  (add-hook 'org-mode-hook
            (lambda ()
              (local-set-key (kbd "C-c M-o") 'bh/mail-subtree)) 'append)
  
  (defun bh/mail-subtree ()
    (interactive)
    (org-mark-subtree)
    (org-mime-subtree))
  
  ;; Enable abbrev-mode
  (add-hook 'org-mode-hook (lambda () (abbrev-mode 1)))
#+end_src
** Organizando Tu Vida EN Archivos Org

Las tareas están separadas en agrupamientos lógicos o proyectos.
Use archivos org separados para grupos de tareas grandes y
subdirectorios para colecciones de archivos de múltiples
proyectos que van de la mano.

Acá hay un ejemplo de los archivos que uso.

Los siguientes archivos org juntan tareas no relacionadas con el trabajo:

| Archivo      | Descripción                                              |
|--------------+----------------------------------------------------------|
| todo.org     | Tareas personales y cosas a las que hacer un seguimiento |
| gsoc2009.org | Cosas para el Google Summer of Code 2009                 |
| farm.org     | Tareas relacionadas a al granja                          |
| mark.org     | Tareas realcionadas con mi hijo Mark                     |
| org.org      | Tareas realacionadas con Org-mode                        |
| git.org      | Tareas relacionadas con Git                              |
| bzflag.org   | Tareas relacionadas con BZFlag                           |

El siguiente archivo org junta capturas de notas y tareas:

| Archivo    | Descripción                 |
|------------+-----------------------------|
| refile.org | Cesto de capturas de tareas |

Los siguientes archivos org contienen mis notas de trabajo (son 
nombres de clientes ficticios)

| Archivos    | Descripción                               |
|-------------+-------------------------------------------|
| norang.org  | Tareas y notas de Norang                  |
| XYZ.org     | Tareas y notas de XYZ corp                |
| ABC.org     | Tareas de ABC Ltd                         |
| ABC-DEF.org | Tareas del cliente DEF corp de la ABC Ltd |
| ABC-KKK.org | Tareas del cliente KKK Inc de la ABC Ltd  |
| YYY.org     | Tareas de YYY                             |

Org-mode es ideal para hacer frente a varios clientes o a proyectos
de los clientes. Un archivo org se convierte en un conjunto de proyectos, notas,
etc para un único cliente o proyecto de los cliente.

La consultora ABC Ltd. tiene varios clientes con los que trabajo.
La separación de las tareas para cada sub-cliente en archivos separados org
ayuda a mantener las cosas agrupados de forma lógica y dado que los clientes van y vienen esto
permite que archivos org completos puedan ser agregados o quitados de mi agenda para mantener
sólo lo que es importante ver en la vista agenda.

Otros archivos org son usados solamente para publicaciones y no contribuyen a la agenda.
Ver Exportaciones y publicaciones para más detalles
** Configuración de la agenda

Este es la configuración actual de =org-agenda-files= (archivos de la agenda)
#+begin_src emacs-lisp :tangle yes
  (setq org-agenda-files (quote ("~/git/org"
                                 "~/git/org/client1"
                                 "~/git/org/bzflag"
                                 "~/git/client2")))
#+end_src

** Estructura de archivos org

** Mapeo de teclado

* Tareas y sus estados

** Palabras claves de TODO

** Selección rápida de TODO

* Agregar nuevas tareas rápidamente con Org Capture

** Templates de captura

** Archivos separados para las capturas de las tareas

** La captura de tareas en sobre todo... ser rápido

* Reclasificación de tareas

** Configuración de la reclasificación

** Reclasificando tareas

** Reclasificando notas

** Reclasificando llamadas

* Vistas de agenda personalizada

